#pragma once

/**********************/
/***** CPU Memory *****/
/**********************/

/* RAM */
#define NES_MEMORY_RAM_START 0x0200
#define NES_MEMORY_RAM_END 0x07FF
#define NES_MEMORY_RAM_SIZE 0x0800

/* I/O Registers */
#define NES_MEMORY_IO_REGISTERS_START 0x2000
#define NES_MEMORY_IO_REGISTERS_END 0x2007

/* Expansion ROM */
#define NES_MEMORY_EXPANSION_ROM_START 0x4020
#define NES_MEMORY_EXPANSION_ROM_END 0x5FFF

/* SRAM */
#define NES_MEMORY_SRAM_START 0x6000
#define NES_MEMORY_SRAM_END 0x7FFF

/* PRG-ROM */
#define NES_MEMORY_PRGROM_START 0x8000
#define NES_MEMORY_PRGROM_END 0xFFFF
#define NES_MEMORY_PRGROM_SIZE 0x8000
#define NES_MEMORY_PRGROM_BANK_SIZE 0x4000
#define NES_MEMORY_PRGROM_UPPER_BANK_START 0xC000
#define NES_MEMORY_PRGROM_LOWER_BANK_END 0xBFFF

/* CHR-ROM */
#define NES_MEMORY_CHRROM_BANK_SIZE 0x2000

/**********************/
/***** PPU Memory *****/
/**********************/

/* Pattern Tables */
#define NES_MEMORY_PPU_PATTERN_TABLE_0_START 0x0000
#define NES_MEMORY_PPU_PATTERN_TABLE_1_START 0x1000
#define NES_MEMORY_PPU_PATTERN_TABLE_0_END 0x0FFF
#define NES_MEMORY_PPU_PATTERN_TABLE_1_END 0x1FFF
#define NES_MEMORY_PPU_PATTERN_TABLE_SIZE 0x1000

/* Name Tables */
#define NES_MEMORY_PPU_NAME_TABLE_0_START 0x2000
#define NES_MEMORY_PPU_NAME_TABLE_1_START 0x2400
#define NES_MEMORY_PPU_NAME_TABLE_2_START 0x2800
#define NES_MEMORY_PPU_NAME_TABLE_3_START 0x2C00
#define NES_MEMORY_PPU_NAME_TABLE_0_END 0x23BF
#define NES_MEMORY_PPU_NAME_TABLE_1_END 0x27BF
#define NES_MEMORY_PPU_NAME_TABLE_2_END 0x2BBF
#define NES_MEMORY_PPU_NAME_TABLE_3_END 0x2FBF
#define NES_MEMORY_PPU_NAME_TABLE_SIZE 0x0400

/* Attribute Tables */
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_0_START 0x23C0
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_1_START 0x27C0
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_2_START 0x2BC0
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_3_START 0x2FC0
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_0_END 0x23FF
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_1_END 0x27FF
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_2_END 0x2BFF
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_3_END 0x2FFF
#define NES_MEMORY_PPU_ATTRIBUTE_TABLE_SIZE 0x0400


/* Palettes */
#define NES_MEMORY_PPU_IMAGE_PALETTE_START 0x3F00
#define NES_MEMORY_PPU_SPRITE_PALETTE_START 0x3F10
#define NES_MEMORY_PPU_PALETTE_SIZE 0x0010