#pragma once

/**********************/
/***** CPU Memory *****/
/**********************/
#define NES_MEMORY_CPU_SIZE 0xFFFF

/* RAM */
#define NES_MEMORY_RAM_START 0x0200
#define NES_MEMORY_RAM_END 0x07FF
#define NES_MEMORY_RAM_SIZE 0x0800

/* Expansion ROM */
#define NES_MEMORY_EXPANSION_ROM_START 0x4020
#define NES_MEMORY_EXPANSION_ROM_END 0x5FFF

/* SRAM */
#define NES_MEMORY_SRAM_START 0x6000
#define NES_MEMORY_SRAM_END 0x7FFF

/* PRG-ROM */
#define NES_MEMORY_PRGROM_SIZE 0x8000
#define NES_MEMORY_PRGROM_BANK_SIZE 0x4000

/* CHR-ROM */
#define NES_MEMORY_CHRROM_BANK_SIZE 0x2000